name: Bug Report
description: File a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: software
    attributes:
      label: Software
      description: What software are you referring to?
      default: Obsidian
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
      default: 0
    validations:
      required: true
  - type: input
    id: pieces-os-version
    attributes:
      label: Your Pieces OS Version
      description: Add the version of Pieces OS installed in your system
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true